create extension if not exists pgcrypto;
create table if not exists public.shopling_price_bulk_jobs (
 id uuid primary key default gen_random_uuid(), owner_id uuid not null, status text not null default 'queued' check (status in ('queued','canary_running','running','paused','completed','completed_with_failures','cancelled')),
 policy_overrides jsonb not null default '[]', retry_of_job_id uuid references public.shopling_price_bulk_jobs(id), canary_passed boolean not null default false,
 last_error text, created_at timestamptz not null default now(), started_at timestamptz, updated_at timestamptz not null default now(), completed_at timestamptz
);
create table if not exists public.shopling_price_bulk_items (
 job_id uuid not null references public.shopling_price_bulk_jobs(id) on delete cascade, goods_key text not null, position integer not null,
 status text not null default 'pending' check (status in ('pending','running','retry_waiting','succeeded','final_failed','cancelled')), attempt integer not null default 0, is_canary boolean not null default false, last_error text,
 primary key(job_id, goods_key)
);
create table if not exists public.shopling_price_bulk_chunks (
 id uuid primary key default gen_random_uuid(), job_id uuid not null references public.shopling_price_bulk_jobs(id) on delete cascade, kind text not null check(kind in ('canary','normal','retry')),
 goods_keys jsonb not null, status text not null default 'pending' check(status in ('pending','dispatching','running','succeeded','retry_waiting','final_failed','blocked','cancelled')),
 attempt integer not null default 0, canary_lineage boolean not null default false, request_id text unique, available_at timestamptz not null default now(), actions_url text, result_summary jsonb, last_error text,
 created_at timestamptz not null default now(), started_at timestamptz, completed_at timestamptz
);
create index if not exists shopling_price_bulk_chunks_active on public.shopling_price_bulk_chunks(status, available_at);
alter table public.shopling_price_bulk_jobs enable row level security; alter table public.shopling_price_bulk_items enable row level security; alter table public.shopling_price_bulk_chunks enable row level security;

create or replace function public.shopling_price_bulk_create_job(p_owner_id uuid,p_goods_keys text[],p_policy_overrides jsonb default '[]',p_retry_of_job_id uuid default null) returns jsonb language plpgsql security definer set search_path=public as $$
declare v_job uuid; v_count int; begin
 if auth.role() <> 'service_role' then raise exception 'service_role required'; end if;
 v_count:=coalesce(array_length(p_goods_keys,1),0); if v_count<1 or v_count>20000 then raise exception 'goods_key count must be 1..20000'; end if;
 if (select count(distinct x) from unnest(p_goods_keys)x)<>v_count or exists(select 1 from unnest(p_goods_keys)x where x!~'^\d+$') then raise exception 'invalid or duplicate goods_key'; end if;
 insert into shopling_price_bulk_jobs(owner_id,policy_overrides,retry_of_job_id) values(p_owner_id,coalesce(p_policy_overrides,'[]'),p_retry_of_job_id) returning id into v_job;
 insert into shopling_price_bulk_items(job_id,goods_key,position,is_canary) select v_job,x,ord,ord<=10 from unnest(p_goods_keys) with ordinality a(x,ord);
 insert into shopling_price_bulk_chunks(job_id,kind,goods_keys,canary_lineage) values(v_job,'canary',to_jsonb(p_goods_keys[1:least(10,v_count)]),true);
 for i in 11..v_count by 50 loop insert into shopling_price_bulk_chunks(job_id,kind,goods_keys) values(v_job,'normal',to_jsonb(p_goods_keys[i:least(i+49,v_count)])); end loop;
 return jsonb_build_object('id',v_job,'status','queued','total',v_count); end $$;

create or replace function public.shopling_price_bulk_active_chunk() returns jsonb language plpgsql security definer set search_path=public as $$ declare c record; begin if auth.role()<>'service_role' then raise exception 'service_role required'; end if; select c.*,j.policy_overrides into c from shopling_price_bulk_chunks c join shopling_price_bulk_jobs j on j.id=c.job_id where c.status in('dispatching','running') order by c.started_at nulls last limit 1; return case when c.id is null then null else to_jsonb(c) end; end $$;

create or replace function public.shopling_price_bulk_claim(p_request_id text) returns jsonb language plpgsql security definer set search_path=public as $$ declare c record; begin
 if auth.role()<>'service_role' then raise exception 'service_role required'; end if; perform pg_advisory_xact_lock(hashtext('shopling_price_bulk_global_one'));
 if exists(select 1 from shopling_price_bulk_chunks where status in('dispatching','running')) then return null; end if;
 select c.*,j.policy_overrides into c from shopling_price_bulk_chunks c join shopling_price_bulk_jobs j on j.id=c.job_id where c.status in('pending','retry_waiting') and c.available_at<=now() and j.status<>'paused' and (c.kind<>'normal' or j.canary_passed) order by case c.kind when 'canary' then 0 when 'retry' then 1 else 2 end,c.created_at for update of c skip locked limit 1;
 if c.id is null then return null; end if; update shopling_price_bulk_chunks set status='dispatching',request_id=p_request_id,started_at=coalesce(started_at,now()) where id=c.id and request_id is null;
 update shopling_price_bulk_items set status='running' where job_id=c.job_id and goods_key in(select jsonb_array_elements_text(c.goods_keys)) and status<>'succeeded';
 update shopling_price_bulk_jobs set status=case when c.canary_lineage then 'canary_running' else 'running' end,started_at=coalesce(started_at,now()),updated_at=now() where id=c.job_id;
 return to_jsonb(c)||jsonb_build_object('request_id',p_request_id); end $$;

create or replace function public.shopling_price_bulk_mark_running(p_chunk_id uuid,p_request_id text,p_actions_url text default null) returns void language plpgsql security definer set search_path=public as $$ begin if auth.role()<>'service_role' then raise exception 'service_role required'; end if; update shopling_price_bulk_chunks set status='running',actions_url=p_actions_url where id=p_chunk_id and status='dispatching' and request_id=p_request_id; if not found then raise exception 'invalid dispatch transition'; end if; end $$;
create or replace function public.shopling_price_bulk_block(p_chunk_id uuid,p_error text) returns void language plpgsql security definer set search_path=public as $$ declare jid uuid; begin if auth.role()<>'service_role' then raise exception 'service_role required'; end if; update shopling_price_bulk_chunks set status='blocked',last_error=p_error,completed_at=now() where id=p_chunk_id returning job_id into jid; update shopling_price_bulk_jobs set status='paused',last_error=p_error,updated_at=now() where id=jid; end $$;

create or replace function public.shopling_price_bulk_finish_chunk(p_chunk_id uuid,p_request_id text,p_failed_keys text[],p_summary jsonb,p_run_url text default null) returns void language plpgsql security definer set search_path=public as $$
declare c record; k text; next_attempt int; retry_keys text[]:='{}'; terminal_count int; item_count int; failed_count int; begin
 if auth.role()<>'service_role' then raise exception 'service_role required'; end if; select * into c from shopling_price_bulk_chunks where id=p_chunk_id and status='running' and request_id=p_request_id for update; if c.id is null then raise exception 'invalid/exact request transition'; end if;
 update shopling_price_bulk_items set status='succeeded',last_error=null where job_id=c.job_id and goods_key in(select jsonb_array_elements_text(c.goods_keys)) and not(goods_key=any(coalesce(p_failed_keys,'{}')));
 foreach k in array coalesce(p_failed_keys,'{}') loop select attempt+1 into next_attempt from shopling_price_bulk_items where job_id=c.job_id and goods_key=k for update; if next_attempt>2 then update shopling_price_bulk_items set status='final_failed',last_error='maximum retry exceeded' where job_id=c.job_id and goods_key=k; else update shopling_price_bulk_items set status='retry_waiting',attempt=next_attempt,last_error='workflow failure' where job_id=c.job_id and goods_key=k; retry_keys:=array_append(retry_keys,k); end if; end loop;
 update shopling_price_bulk_chunks set status=case when cardinality(coalesce(p_failed_keys,'{}'))=0 then 'succeeded' when cardinality(retry_keys)>0 then 'retry_waiting' else 'final_failed' end,result_summary=p_summary,actions_url=coalesce(p_run_url,actions_url),completed_at=now() where id=c.id;
 if cardinality(retry_keys)>0 then insert into shopling_price_bulk_chunks(job_id,kind,goods_keys,status,attempt,canary_lineage,available_at) values(c.job_id,'retry',to_jsonb(retry_keys),'retry_waiting',next_attempt,c.canary_lineage,now()+make_interval(mins=>case when next_attempt=1 then 5 else 10 end)); end if;
 if c.canary_lineage and cardinality(coalesce(p_failed_keys,'{}'))>0 then update shopling_price_bulk_jobs set status='paused',last_error='카나리 실패: 재개 후 카나리 실패 상품만 재시도합니다.',updated_at=now() where id=c.job_id; elsif c.canary_lineage and not exists(select 1 from shopling_price_bulk_items where job_id=c.job_id and is_canary and status<>'succeeded') then update shopling_price_bulk_jobs set canary_passed=true,status='running',updated_at=now() where id=c.job_id; end if;
 select count(*),count(*) filter(where status in('succeeded','final_failed')),count(*) filter(where status='final_failed') into item_count,terminal_count,failed_count from shopling_price_bulk_items where job_id=c.job_id;
 if terminal_count=item_count and not exists(select 1 from shopling_price_bulk_chunks where job_id=c.job_id and status in('pending','dispatching','running','retry_waiting')) then update shopling_price_bulk_jobs set status=case when failed_count>0 then 'completed_with_failures' else 'completed' end,completed_at=now(),updated_at=now() where id=c.job_id; end if;
 end $$;

create or replace function public.shopling_price_bulk_pause(p_job_id uuid,p_owner_id uuid) returns jsonb language plpgsql security definer set search_path=public as $$ begin if auth.role()<>'service_role' then raise exception 'service_role required'; end if; update shopling_price_bulk_jobs set status='paused',updated_at=now() where id=p_job_id and owner_id=p_owner_id and status in('queued','canary_running','running'); if not found then raise exception 'pause invalid state or forbidden'; end if; return jsonb_build_object('id',p_job_id,'status','paused'); end $$;
create or replace function public.shopling_price_bulk_resume(p_job_id uuid,p_owner_id uuid) returns jsonb language plpgsql security definer set search_path=public as $$ declare j record; begin if auth.role()<>'service_role' then raise exception 'service_role required'; end if; select * into j from shopling_price_bulk_jobs where id=p_job_id and owner_id=p_owner_id for update; if j.status<>'paused' or exists(select 1 from shopling_price_bulk_chunks where job_id=p_job_id and status='blocked') then raise exception 'blocked 원인을 확인하거나 paused 상태인지 확인하세요'; end if; update shopling_price_bulk_jobs set status=case when j.canary_passed then 'running' else 'queued' end,updated_at=now() where id=p_job_id; return jsonb_build_object('id',p_job_id,'status',case when j.canary_passed then 'running' else 'queued' end); end $$;
create or replace function public.shopling_price_bulk_job_detail(p_job_id uuid,p_owner_id uuid) returns jsonb language sql security definer set search_path=public as $$ select jsonb_build_object('id',j.id,'status',j.status,'created_at',j.created_at,'started_at',j.started_at,'updated_at',j.updated_at,'completed_at',j.completed_at,'last_error',j.last_error,'retry_of_job_id',j.retry_of_job_id,'counts',(select jsonb_build_object('total',count(*),'succeeded',count(*)filter(where status='succeeded'),'final_failed',count(*)filter(where status='final_failed'),'retry_waiting',count(*)filter(where status='retry_waiting'),'running',count(*)filter(where status='running'),'retry_succeeded',count(*)filter(where status='succeeded' and attempt>0)) from shopling_price_bulk_items where job_id=j.id),'current_chunk',(select jsonb_build_object('kind',kind,'goods_key_count',jsonb_array_length(goods_keys),'request_id',request_id,'actions_url',actions_url,'status',status) from shopling_price_bulk_chunks where job_id=j.id and status in('dispatching','running','blocked') order by started_at desc nulls last limit 1),'chunk_stats',(select jsonb_build_object('total_attempts',count(*),'terminal',count(*) filter(where status in('succeeded','final_failed','blocked','cancelled'))) from shopling_price_bulk_chunks where job_id=j.id)) from shopling_price_bulk_jobs j where j.id=p_job_id and j.owner_id=p_owner_id and auth.role()='service_role' $$;
create or replace function public.shopling_price_bulk_recent_jobs(p_owner_id uuid) returns jsonb language sql security definer set search_path=public as $$ select coalesce(jsonb_agg(x order by created_at desc),'[]') from(select j.id,j.status,j.created_at,count(i.*) total,count(i.*)filter(where i.status='succeeded') succeeded,count(i.*)filter(where i.status='final_failed') final_failed from shopling_price_bulk_jobs j left join shopling_price_bulk_items i on i.job_id=j.id where j.owner_id=p_owner_id and auth.role()='service_role' group by j.id order by j.created_at desc limit 10)x $$;
create or replace function public.shopling_price_bulk_retry_failed(p_job_id uuid,p_owner_id uuid) returns jsonb language plpgsql security definer set search_path=public as $$ declare keys text[]; policies jsonb; new_job jsonb; begin if auth.role()<>'service_role' then raise exception 'service_role required'; end if; select array_agg(i.goods_key order by i.position),j.policy_overrides into keys,policies from shopling_price_bulk_jobs j join shopling_price_bulk_items i on i.job_id=j.id and i.status='final_failed' where j.id=p_job_id and j.owner_id=p_owner_id group by j.policy_overrides; if cardinality(keys)=0 or keys is null then raise exception 'final_failed 상품이 없습니다.'; end if; return shopling_price_bulk_create_job(p_owner_id,keys,policies,p_job_id); end $$;
revoke all on function public.shopling_price_bulk_create_job(uuid,text[],jsonb,uuid),public.shopling_price_bulk_active_chunk(),public.shopling_price_bulk_claim(text),public.shopling_price_bulk_mark_running(uuid,text,text),public.shopling_price_bulk_block(uuid,text),public.shopling_price_bulk_finish_chunk(uuid,text,text[],jsonb,text),public.shopling_price_bulk_pause(uuid,uuid),public.shopling_price_bulk_resume(uuid,uuid),public.shopling_price_bulk_job_detail(uuid,uuid),public.shopling_price_bulk_recent_jobs(uuid),public.shopling_price_bulk_retry_failed(uuid,uuid) from public, anon, authenticated;
grant execute on function public.shopling_price_bulk_create_job(uuid,text[],jsonb,uuid),public.shopling_price_bulk_active_chunk(),public.shopling_price_bulk_claim(text),public.shopling_price_bulk_mark_running(uuid,text,text),public.shopling_price_bulk_block(uuid,text),public.shopling_price_bulk_finish_chunk(uuid,text,text[],jsonb,text),public.shopling_price_bulk_pause(uuid,uuid),public.shopling_price_bulk_resume(uuid,uuid),public.shopling_price_bulk_job_detail(uuid,uuid),public.shopling_price_bulk_recent_jobs(uuid),public.shopling_price_bulk_retry_failed(uuid,uuid) to service_role;
